//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinForm.NhaSXServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NhaSX", Namespace="http://schemas.datacontract.org/2004/07/WcfServices")]
    [System.SerializableAttribute()]
    public partial class NhaSX : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NhaSX_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenNhaSXField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NhaSX_ID {
            get {
                return this.NhaSX_IDField;
            }
            set {
                if ((this.NhaSX_IDField.Equals(value) != true)) {
                    this.NhaSX_IDField = value;
                    this.RaisePropertyChanged("NhaSX_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenNhaSX {
            get {
                return this.TenNhaSXField;
            }
            set {
                if ((object.ReferenceEquals(this.TenNhaSXField, value) != true)) {
                    this.TenNhaSXField = value;
                    this.RaisePropertyChanged("TenNhaSX");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NhaSXServiceReference.INhaSXService")]
    public interface INhaSXService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INhaSXService/HienThiNhaSX", ReplyAction="http://tempuri.org/INhaSXService/HienThiNhaSXResponse")]
        WinForm.NhaSXServiceReference.NhaSX[] HienThiNhaSX();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INhaSXService/Them", ReplyAction="http://tempuri.org/INhaSXService/ThemResponse")]
        void Them(WinForm.NhaSXServiceReference.NhaSX nsx);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INhaSXService/Sua", ReplyAction="http://tempuri.org/INhaSXService/SuaResponse")]
        void Sua(WinForm.NhaSXServiceReference.NhaSX nsx);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INhaSXService/Xoa", ReplyAction="http://tempuri.org/INhaSXService/XoaResponse")]
        void Xoa(WinForm.NhaSXServiceReference.NhaSX nsx);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INhaSXServiceChannel : WinForm.NhaSXServiceReference.INhaSXService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NhaSXServiceClient : System.ServiceModel.ClientBase<WinForm.NhaSXServiceReference.INhaSXService>, WinForm.NhaSXServiceReference.INhaSXService {
        
        public NhaSXServiceClient() {
        }
        
        public NhaSXServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NhaSXServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NhaSXServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NhaSXServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WinForm.NhaSXServiceReference.NhaSX[] HienThiNhaSX() {
            return base.Channel.HienThiNhaSX();
        }
        
        public void Them(WinForm.NhaSXServiceReference.NhaSX nsx) {
            base.Channel.Them(nsx);
        }
        
        public void Sua(WinForm.NhaSXServiceReference.NhaSX nsx) {
            base.Channel.Sua(nsx);
        }
        
        public void Xoa(WinForm.NhaSXServiceReference.NhaSX nsx) {
            base.Channel.Xoa(nsx);
        }
    }
}
