//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebForm.NguoiDungServiceReference {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NguoiDungServiceReference.INguoiDungService")]
    public interface INguoiDungService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INguoiDungService/DoWork", ReplyAction="http://tempuri.org/INguoiDungService/DoWorkResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void DoWork();
        
        // CODEGEN: Parameter 'ng' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INguoiDungService/Them", ReplyAction="http://tempuri.org/INguoiDungService/ThemResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebForm.NguoiDungServiceReference.ThemResponse Them(WebForm.NguoiDungServiceReference.ThemRequest request);
        
        // CODEGEN: Parameter 'tendangnhap' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INguoiDungService/DangNhap", ReplyAction="http://tempuri.org/INguoiDungService/DangNhapResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebForm.NguoiDungServiceReference.DangNhapResponse DangNhap(WebForm.NguoiDungServiceReference.DangNhapRequest request);
        
        // CODEGEN: Parameter 'ThongTinNguoiDungResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INguoiDungService/ThongTinNguoiDung", ReplyAction="http://tempuri.org/INguoiDungService/ThongTinNguoiDungResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebForm.NguoiDungServiceReference.ThongTinNguoiDungResponse ThongTinNguoiDung(WebForm.NguoiDungServiceReference.ThongTinNguoiDungRequest request);
        
        // CODEGEN: Parameter 'ThongTinNguoiDung_IDResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INguoiDungService/ThongTinNguoiDung_ID", ReplyAction="http://tempuri.org/INguoiDungService/ThongTinNguoiDung_IDResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebForm.NguoiDungServiceReference.ThongTinNguoiDung_IDResponse ThongTinNguoiDung_ID(WebForm.NguoiDungServiceReference.ThongTinNguoiDung_IDRequest request);
        
        // CODEGEN: Parameter 'ng' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INguoiDungService/CapNhatThongTin", ReplyAction="http://tempuri.org/INguoiDungService/CapNhatThongTinResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebForm.NguoiDungServiceReference.CapNhatThongTinResponse CapNhatThongTin(WebForm.NguoiDungServiceReference.CapNhatThongTinRequest request);
        
        // CODEGEN: Parameter 'MatKhau' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INguoiDungService/DoiMatKhau", ReplyAction="http://tempuri.org/INguoiDungService/DoiMatKhauResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebForm.NguoiDungServiceReference.DoiMatKhauResponse DoiMatKhau(WebForm.NguoiDungServiceReference.DoiMatKhauRequest request);
        
        // CODEGEN: Parameter 'MatKhau' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INguoiDungService/KT_MatKhau", ReplyAction="http://tempuri.org/INguoiDungService/KT_MatKhauResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebForm.NguoiDungServiceReference.KT_MatKhauResponse KT_MatKhau(WebForm.NguoiDungServiceReference.KT_MatKhauRequest request);
        
        // CODEGEN: Parameter 'Email' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INguoiDungService/IsEmail", ReplyAction="http://tempuri.org/INguoiDungService/IsEmailResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebForm.NguoiDungServiceReference.IsEmailResponse IsEmail(WebForm.NguoiDungServiceReference.IsEmailRequest request);
        
        // CODEGEN: Parameter 'TenDangNhap' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INguoiDungService/IsTenDangNhap", ReplyAction="http://tempuri.org/INguoiDungService/IsTenDangNhapResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebForm.NguoiDungServiceReference.IsTenDangNhapResponse IsTenDangNhap(WebForm.NguoiDungServiceReference.IsTenDangNhapRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WcfServices")]
    public partial class NguoiDung : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string diaChiField;
        
        private string emailField;
        
        private int idField;
        
        private bool idFieldSpecified;
        
        private string matKhauField;
        
        private int quyenField;
        
        private bool quyenFieldSpecified;
        
        private string soDienThoaiField;
        
        private string tenField;
        
        private string tenDangNhapField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string DiaChi {
            get {
                return this.diaChiField;
            }
            set {
                this.diaChiField = value;
                this.RaisePropertyChanged("DiaChi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("Email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IDSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("IDSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string MatKhau {
            get {
                return this.matKhauField;
            }
            set {
                this.matKhauField = value;
                this.RaisePropertyChanged("MatKhau");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int Quyen {
            get {
                return this.quyenField;
            }
            set {
                this.quyenField = value;
                this.RaisePropertyChanged("Quyen");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool QuyenSpecified {
            get {
                return this.quyenFieldSpecified;
            }
            set {
                this.quyenFieldSpecified = value;
                this.RaisePropertyChanged("QuyenSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string SoDienThoai {
            get {
                return this.soDienThoaiField;
            }
            set {
                this.soDienThoaiField = value;
                this.RaisePropertyChanged("SoDienThoai");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string Ten {
            get {
                return this.tenField;
            }
            set {
                this.tenField = value;
                this.RaisePropertyChanged("Ten");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string TenDangNhap {
            get {
                return this.tenDangNhapField;
            }
            set {
                this.tenDangNhapField = value;
                this.RaisePropertyChanged("TenDangNhap");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Them", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ThemRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public WebForm.NguoiDungServiceReference.NguoiDung ng;
        
        public ThemRequest() {
        }
        
        public ThemRequest(WebForm.NguoiDungServiceReference.NguoiDung ng) {
            this.ng = ng;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ThemResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ThemResponse {
        
        public ThemResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DangNhap", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DangNhapRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string tendangnhap;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string matkhau;
        
        public DangNhapRequest() {
        }
        
        public DangNhapRequest(string tendangnhap, string matkhau) {
            this.tendangnhap = tendangnhap;
            this.matkhau = matkhau;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DangNhapResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DangNhapResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool DangNhapResult;
        
        public DangNhapResponse() {
        }
        
        public DangNhapResponse(bool DangNhapResult) {
            this.DangNhapResult = DangNhapResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ThongTinNguoiDung", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ThongTinNguoiDungRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string tenDangNhap;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string matKhau;
        
        public ThongTinNguoiDungRequest() {
        }
        
        public ThongTinNguoiDungRequest(string tenDangNhap, string matKhau) {
            this.tenDangNhap = tenDangNhap;
            this.matKhau = matKhau;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ThongTinNguoiDungResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ThongTinNguoiDungResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataSet ThongTinNguoiDungResult;
        
        public ThongTinNguoiDungResponse() {
        }
        
        public ThongTinNguoiDungResponse(System.Data.DataSet ThongTinNguoiDungResult) {
            this.ThongTinNguoiDungResult = ThongTinNguoiDungResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ThongTinNguoiDung_ID", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ThongTinNguoiDung_IDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int ID;
        
        public ThongTinNguoiDung_IDRequest() {
        }
        
        public ThongTinNguoiDung_IDRequest(int ID) {
            this.ID = ID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ThongTinNguoiDung_IDResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ThongTinNguoiDung_IDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataSet ThongTinNguoiDung_IDResult;
        
        public ThongTinNguoiDung_IDResponse() {
        }
        
        public ThongTinNguoiDung_IDResponse(System.Data.DataSet ThongTinNguoiDung_IDResult) {
            this.ThongTinNguoiDung_IDResult = ThongTinNguoiDung_IDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CapNhatThongTin", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CapNhatThongTinRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public WebForm.NguoiDungServiceReference.NguoiDung ng;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int ID;
        
        public CapNhatThongTinRequest() {
        }
        
        public CapNhatThongTinRequest(WebForm.NguoiDungServiceReference.NguoiDung ng, int ID) {
            this.ng = ng;
            this.ID = ID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CapNhatThongTinResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CapNhatThongTinResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool CapNhatThongTinResult;
        
        public CapNhatThongTinResponse() {
        }
        
        public CapNhatThongTinResponse(bool CapNhatThongTinResult) {
            this.CapNhatThongTinResult = CapNhatThongTinResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DoiMatKhau", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DoiMatKhauRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MatKhau;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int ID;
        
        public DoiMatKhauRequest() {
        }
        
        public DoiMatKhauRequest(string MatKhau, int ID) {
            this.MatKhau = MatKhau;
            this.ID = ID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DoiMatKhauResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DoiMatKhauResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool DoiMatKhauResult;
        
        public DoiMatKhauResponse() {
        }
        
        public DoiMatKhauResponse(bool DoiMatKhauResult) {
            this.DoiMatKhauResult = DoiMatKhauResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="KT_MatKhau", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class KT_MatKhauRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MatKhau;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int ID;
        
        public KT_MatKhauRequest() {
        }
        
        public KT_MatKhauRequest(string MatKhau, int ID) {
            this.MatKhau = MatKhau;
            this.ID = ID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="KT_MatKhauResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class KT_MatKhauResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool KT_MatKhauResult;
        
        public KT_MatKhauResponse() {
        }
        
        public KT_MatKhauResponse(bool KT_MatKhauResult) {
            this.KT_MatKhauResult = KT_MatKhauResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsEmail", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class IsEmailRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Email;
        
        public IsEmailRequest() {
        }
        
        public IsEmailRequest(string Email) {
            this.Email = Email;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsEmailResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class IsEmailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool IsEmailResult;
        
        public IsEmailResponse() {
        }
        
        public IsEmailResponse(bool IsEmailResult) {
            this.IsEmailResult = IsEmailResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsTenDangNhap", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class IsTenDangNhapRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TenDangNhap;
        
        public IsTenDangNhapRequest() {
        }
        
        public IsTenDangNhapRequest(string TenDangNhap) {
            this.TenDangNhap = TenDangNhap;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsTenDangNhapResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class IsTenDangNhapResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool IsTenDangNhapResult;
        
        public IsTenDangNhapResponse() {
        }
        
        public IsTenDangNhapResponse(bool IsTenDangNhapResult) {
            this.IsTenDangNhapResult = IsTenDangNhapResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INguoiDungServiceChannel : WebForm.NguoiDungServiceReference.INguoiDungService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NguoiDungServiceClient : System.ServiceModel.ClientBase<WebForm.NguoiDungServiceReference.INguoiDungService>, WebForm.NguoiDungServiceReference.INguoiDungService {
        
        public NguoiDungServiceClient() {
        }
        
        public NguoiDungServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NguoiDungServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NguoiDungServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NguoiDungServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebForm.NguoiDungServiceReference.ThemResponse WebForm.NguoiDungServiceReference.INguoiDungService.Them(WebForm.NguoiDungServiceReference.ThemRequest request) {
            return base.Channel.Them(request);
        }
        
        public void Them(WebForm.NguoiDungServiceReference.NguoiDung ng) {
            WebForm.NguoiDungServiceReference.ThemRequest inValue = new WebForm.NguoiDungServiceReference.ThemRequest();
            inValue.ng = ng;
            WebForm.NguoiDungServiceReference.ThemResponse retVal = ((WebForm.NguoiDungServiceReference.INguoiDungService)(this)).Them(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebForm.NguoiDungServiceReference.DangNhapResponse WebForm.NguoiDungServiceReference.INguoiDungService.DangNhap(WebForm.NguoiDungServiceReference.DangNhapRequest request) {
            return base.Channel.DangNhap(request);
        }
        
        public bool DangNhap(string tendangnhap, string matkhau) {
            WebForm.NguoiDungServiceReference.DangNhapRequest inValue = new WebForm.NguoiDungServiceReference.DangNhapRequest();
            inValue.tendangnhap = tendangnhap;
            inValue.matkhau = matkhau;
            WebForm.NguoiDungServiceReference.DangNhapResponse retVal = ((WebForm.NguoiDungServiceReference.INguoiDungService)(this)).DangNhap(inValue);
            return retVal.DangNhapResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebForm.NguoiDungServiceReference.ThongTinNguoiDungResponse WebForm.NguoiDungServiceReference.INguoiDungService.ThongTinNguoiDung(WebForm.NguoiDungServiceReference.ThongTinNguoiDungRequest request) {
            return base.Channel.ThongTinNguoiDung(request);
        }
        
        public System.Data.DataSet ThongTinNguoiDung(string tenDangNhap, string matKhau) {
            WebForm.NguoiDungServiceReference.ThongTinNguoiDungRequest inValue = new WebForm.NguoiDungServiceReference.ThongTinNguoiDungRequest();
            inValue.tenDangNhap = tenDangNhap;
            inValue.matKhau = matKhau;
            WebForm.NguoiDungServiceReference.ThongTinNguoiDungResponse retVal = ((WebForm.NguoiDungServiceReference.INguoiDungService)(this)).ThongTinNguoiDung(inValue);
            return retVal.ThongTinNguoiDungResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebForm.NguoiDungServiceReference.ThongTinNguoiDung_IDResponse WebForm.NguoiDungServiceReference.INguoiDungService.ThongTinNguoiDung_ID(WebForm.NguoiDungServiceReference.ThongTinNguoiDung_IDRequest request) {
            return base.Channel.ThongTinNguoiDung_ID(request);
        }
        
        public System.Data.DataSet ThongTinNguoiDung_ID(int ID) {
            WebForm.NguoiDungServiceReference.ThongTinNguoiDung_IDRequest inValue = new WebForm.NguoiDungServiceReference.ThongTinNguoiDung_IDRequest();
            inValue.ID = ID;
            WebForm.NguoiDungServiceReference.ThongTinNguoiDung_IDResponse retVal = ((WebForm.NguoiDungServiceReference.INguoiDungService)(this)).ThongTinNguoiDung_ID(inValue);
            return retVal.ThongTinNguoiDung_IDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebForm.NguoiDungServiceReference.CapNhatThongTinResponse WebForm.NguoiDungServiceReference.INguoiDungService.CapNhatThongTin(WebForm.NguoiDungServiceReference.CapNhatThongTinRequest request) {
            return base.Channel.CapNhatThongTin(request);
        }
        
        public bool CapNhatThongTin(WebForm.NguoiDungServiceReference.NguoiDung ng, int ID) {
            WebForm.NguoiDungServiceReference.CapNhatThongTinRequest inValue = new WebForm.NguoiDungServiceReference.CapNhatThongTinRequest();
            inValue.ng = ng;
            inValue.ID = ID;
            WebForm.NguoiDungServiceReference.CapNhatThongTinResponse retVal = ((WebForm.NguoiDungServiceReference.INguoiDungService)(this)).CapNhatThongTin(inValue);
            return retVal.CapNhatThongTinResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebForm.NguoiDungServiceReference.DoiMatKhauResponse WebForm.NguoiDungServiceReference.INguoiDungService.DoiMatKhau(WebForm.NguoiDungServiceReference.DoiMatKhauRequest request) {
            return base.Channel.DoiMatKhau(request);
        }
        
        public bool DoiMatKhau(string MatKhau, int ID) {
            WebForm.NguoiDungServiceReference.DoiMatKhauRequest inValue = new WebForm.NguoiDungServiceReference.DoiMatKhauRequest();
            inValue.MatKhau = MatKhau;
            inValue.ID = ID;
            WebForm.NguoiDungServiceReference.DoiMatKhauResponse retVal = ((WebForm.NguoiDungServiceReference.INguoiDungService)(this)).DoiMatKhau(inValue);
            return retVal.DoiMatKhauResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebForm.NguoiDungServiceReference.KT_MatKhauResponse WebForm.NguoiDungServiceReference.INguoiDungService.KT_MatKhau(WebForm.NguoiDungServiceReference.KT_MatKhauRequest request) {
            return base.Channel.KT_MatKhau(request);
        }
        
        public bool KT_MatKhau(string MatKhau, int ID) {
            WebForm.NguoiDungServiceReference.KT_MatKhauRequest inValue = new WebForm.NguoiDungServiceReference.KT_MatKhauRequest();
            inValue.MatKhau = MatKhau;
            inValue.ID = ID;
            WebForm.NguoiDungServiceReference.KT_MatKhauResponse retVal = ((WebForm.NguoiDungServiceReference.INguoiDungService)(this)).KT_MatKhau(inValue);
            return retVal.KT_MatKhauResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebForm.NguoiDungServiceReference.IsEmailResponse WebForm.NguoiDungServiceReference.INguoiDungService.IsEmail(WebForm.NguoiDungServiceReference.IsEmailRequest request) {
            return base.Channel.IsEmail(request);
        }
        
        public bool IsEmail(string Email) {
            WebForm.NguoiDungServiceReference.IsEmailRequest inValue = new WebForm.NguoiDungServiceReference.IsEmailRequest();
            inValue.Email = Email;
            WebForm.NguoiDungServiceReference.IsEmailResponse retVal = ((WebForm.NguoiDungServiceReference.INguoiDungService)(this)).IsEmail(inValue);
            return retVal.IsEmailResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebForm.NguoiDungServiceReference.IsTenDangNhapResponse WebForm.NguoiDungServiceReference.INguoiDungService.IsTenDangNhap(WebForm.NguoiDungServiceReference.IsTenDangNhapRequest request) {
            return base.Channel.IsTenDangNhap(request);
        }
        
        public bool IsTenDangNhap(string TenDangNhap) {
            WebForm.NguoiDungServiceReference.IsTenDangNhapRequest inValue = new WebForm.NguoiDungServiceReference.IsTenDangNhapRequest();
            inValue.TenDangNhap = TenDangNhap;
            WebForm.NguoiDungServiceReference.IsTenDangNhapResponse retVal = ((WebForm.NguoiDungServiceReference.INguoiDungService)(this)).IsTenDangNhap(inValue);
            return retVal.IsTenDangNhapResult;
        }
    }
}
