//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinForm.CtPhieuNhapServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CtPhieuNhap", Namespace="http://schemas.datacontract.org/2004/07/WcfServices")]
    [System.SerializableAttribute()]
    public partial class CtPhieuNhap : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float DonGiaNhapField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaPhieuNhapField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SP_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SoLuongNhapField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenSPField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float DonGiaNhap {
            get {
                return this.DonGiaNhapField;
            }
            set {
                if ((this.DonGiaNhapField.Equals(value) != true)) {
                    this.DonGiaNhapField = value;
                    this.RaisePropertyChanged("DonGiaNhap");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaPhieuNhap {
            get {
                return this.MaPhieuNhapField;
            }
            set {
                if ((object.ReferenceEquals(this.MaPhieuNhapField, value) != true)) {
                    this.MaPhieuNhapField = value;
                    this.RaisePropertyChanged("MaPhieuNhap");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SP_ID {
            get {
                return this.SP_IDField;
            }
            set {
                if ((this.SP_IDField.Equals(value) != true)) {
                    this.SP_IDField = value;
                    this.RaisePropertyChanged("SP_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SoLuongNhap {
            get {
                return this.SoLuongNhapField;
            }
            set {
                if ((this.SoLuongNhapField.Equals(value) != true)) {
                    this.SoLuongNhapField = value;
                    this.RaisePropertyChanged("SoLuongNhap");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenSP {
            get {
                return this.TenSPField;
            }
            set {
                if ((object.ReferenceEquals(this.TenSPField, value) != true)) {
                    this.TenSPField = value;
                    this.RaisePropertyChanged("TenSP");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CtPhieuNhapServiceReference.ICtPhieuNhapService")]
    public interface ICtPhieuNhapService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICtPhieuNhapService/HienThiCtPhieuNhap", ReplyAction="http://tempuri.org/ICtPhieuNhapService/HienThiCtPhieuNhapResponse")]
        WinForm.CtPhieuNhapServiceReference.CtPhieuNhap[] HienThiCtPhieuNhap(WinForm.CtPhieuNhapServiceReference.CtPhieuNhap ct);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICtPhieuNhapService/KiemTraMaPhieuNhap", ReplyAction="http://tempuri.org/ICtPhieuNhapService/KiemTraMaPhieuNhapResponse")]
        bool KiemTraMaPhieuNhap(string ma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICtPhieuNhapService/Them", ReplyAction="http://tempuri.org/ICtPhieuNhapService/ThemResponse")]
        void Them(WinForm.CtPhieuNhapServiceReference.CtPhieuNhap ct);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICtPhieuNhapServiceChannel : WinForm.CtPhieuNhapServiceReference.ICtPhieuNhapService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CtPhieuNhapServiceClient : System.ServiceModel.ClientBase<WinForm.CtPhieuNhapServiceReference.ICtPhieuNhapService>, WinForm.CtPhieuNhapServiceReference.ICtPhieuNhapService {
        
        public CtPhieuNhapServiceClient() {
        }
        
        public CtPhieuNhapServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CtPhieuNhapServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CtPhieuNhapServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CtPhieuNhapServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WinForm.CtPhieuNhapServiceReference.CtPhieuNhap[] HienThiCtPhieuNhap(WinForm.CtPhieuNhapServiceReference.CtPhieuNhap ct) {
            return base.Channel.HienThiCtPhieuNhap(ct);
        }
        
        public bool KiemTraMaPhieuNhap(string ma) {
            return base.Channel.KiemTraMaPhieuNhap(ma);
        }
        
        public void Them(WinForm.CtPhieuNhapServiceReference.CtPhieuNhap ct) {
            base.Channel.Them(ct);
        }
    }
}
