//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebForm.SanPhamServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SanPham", Namespace="http://schemas.datacontract.org/2004/07/WcfServices")]
    [System.SerializableAttribute()]
    public partial class SanPham : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BaoHanhField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CPUField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float DonGiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HDDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HinhField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MoTaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NhaSX_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RAMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SP_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenSPField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BaoHanh {
            get {
                return this.BaoHanhField;
            }
            set {
                if ((object.ReferenceEquals(this.BaoHanhField, value) != true)) {
                    this.BaoHanhField = value;
                    this.RaisePropertyChanged("BaoHanh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CPU {
            get {
                return this.CPUField;
            }
            set {
                if ((object.ReferenceEquals(this.CPUField, value) != true)) {
                    this.CPUField = value;
                    this.RaisePropertyChanged("CPU");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float DonGia {
            get {
                return this.DonGiaField;
            }
            set {
                if ((this.DonGiaField.Equals(value) != true)) {
                    this.DonGiaField = value;
                    this.RaisePropertyChanged("DonGia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HDD {
            get {
                return this.HDDField;
            }
            set {
                if ((object.ReferenceEquals(this.HDDField, value) != true)) {
                    this.HDDField = value;
                    this.RaisePropertyChanged("HDD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Hinh {
            get {
                return this.HinhField;
            }
            set {
                if ((object.ReferenceEquals(this.HinhField, value) != true)) {
                    this.HinhField = value;
                    this.RaisePropertyChanged("Hinh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MoTa {
            get {
                return this.MoTaField;
            }
            set {
                if ((object.ReferenceEquals(this.MoTaField, value) != true)) {
                    this.MoTaField = value;
                    this.RaisePropertyChanged("MoTa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NhaSX_ID {
            get {
                return this.NhaSX_IDField;
            }
            set {
                if ((this.NhaSX_IDField.Equals(value) != true)) {
                    this.NhaSX_IDField = value;
                    this.RaisePropertyChanged("NhaSX_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RAM {
            get {
                return this.RAMField;
            }
            set {
                if ((object.ReferenceEquals(this.RAMField, value) != true)) {
                    this.RAMField = value;
                    this.RaisePropertyChanged("RAM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SP_ID {
            get {
                return this.SP_IDField;
            }
            set {
                if ((this.SP_IDField.Equals(value) != true)) {
                    this.SP_IDField = value;
                    this.RaisePropertyChanged("SP_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenSP {
            get {
                return this.TenSPField;
            }
            set {
                if ((object.ReferenceEquals(this.TenSPField, value) != true)) {
                    this.TenSPField = value;
                    this.RaisePropertyChanged("TenSP");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PhieuNhap", Namespace="http://schemas.datacontract.org/2004/07/WcfServices")]
    [System.SerializableAttribute()]
    public partial class PhieuNhap : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaPhieuNhapField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime NgayNhapField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NhaSX_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PhieuNhap_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenNhaSXField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float TongTienField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaPhieuNhap {
            get {
                return this.MaPhieuNhapField;
            }
            set {
                if ((object.ReferenceEquals(this.MaPhieuNhapField, value) != true)) {
                    this.MaPhieuNhapField = value;
                    this.RaisePropertyChanged("MaPhieuNhap");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime NgayNhap {
            get {
                return this.NgayNhapField;
            }
            set {
                if ((this.NgayNhapField.Equals(value) != true)) {
                    this.NgayNhapField = value;
                    this.RaisePropertyChanged("NgayNhap");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NhaSX_ID {
            get {
                return this.NhaSX_IDField;
            }
            set {
                if ((this.NhaSX_IDField.Equals(value) != true)) {
                    this.NhaSX_IDField = value;
                    this.RaisePropertyChanged("NhaSX_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PhieuNhap_ID {
            get {
                return this.PhieuNhap_IDField;
            }
            set {
                if ((this.PhieuNhap_IDField.Equals(value) != true)) {
                    this.PhieuNhap_IDField = value;
                    this.RaisePropertyChanged("PhieuNhap_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenNhaSX {
            get {
                return this.TenNhaSXField;
            }
            set {
                if ((object.ReferenceEquals(this.TenNhaSXField, value) != true)) {
                    this.TenNhaSXField = value;
                    this.RaisePropertyChanged("TenNhaSX");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float TongTien {
            get {
                return this.TongTienField;
            }
            set {
                if ((this.TongTienField.Equals(value) != true)) {
                    this.TongTienField = value;
                    this.RaisePropertyChanged("TongTien");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SanPhamServiceReference.ISanPhamService")]
    public interface ISanPhamService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISanPhamService/LaySP_ID", ReplyAction="http://tempuri.org/ISanPhamService/LaySP_IDResponse")]
        System.Data.DataSet LaySP_ID();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISanPhamService/HienThiSanPhamFull", ReplyAction="http://tempuri.org/ISanPhamService/HienThiSanPhamFullResponse")]
        WebForm.SanPhamServiceReference.SanPham[] HienThiSanPhamFull();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISanPhamService/HienThiSanPhamMoi", ReplyAction="http://tempuri.org/ISanPhamService/HienThiSanPhamMoiResponse")]
        WebForm.SanPhamServiceReference.SanPham[] HienThiSanPhamMoi();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISanPhamService/HienThiSanPhamCungLoai", ReplyAction="http://tempuri.org/ISanPhamService/HienThiSanPhamCungLoaiResponse")]
        WebForm.SanPhamServiceReference.SanPham[] HienThiSanPhamCungLoai(WebForm.SanPhamServiceReference.SanPham sp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISanPhamService/HienThiSanPhamNhaSX", ReplyAction="http://tempuri.org/ISanPhamService/HienThiSanPhamNhaSXResponse")]
        WebForm.SanPhamServiceReference.SanPham[] HienThiSanPhamNhaSX(WebForm.SanPhamServiceReference.SanPham sp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISanPhamService/TimKiemSanPham", ReplyAction="http://tempuri.org/ISanPhamService/TimKiemSanPhamResponse")]
        WebForm.SanPhamServiceReference.SanPham[] TimKiemSanPham(string tensp, int nhasxid, decimal dongiatu, decimal dongiaden);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISanPhamService/ChiTietSanPham", ReplyAction="http://tempuri.org/ISanPhamService/ChiTietSanPhamResponse")]
        System.Data.DataSet ChiTietSanPham(WebForm.SanPhamServiceReference.SanPham sp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISanPhamService/ThongTinNhapSP", ReplyAction="http://tempuri.org/ISanPhamService/ThongTinNhapSPResponse")]
        System.Data.DataSet ThongTinNhapSP(WebForm.SanPhamServiceReference.PhieuNhap pn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISanPhamService/Them", ReplyAction="http://tempuri.org/ISanPhamService/ThemResponse")]
        void Them(WebForm.SanPhamServiceReference.SanPham sp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISanPhamService/Sua", ReplyAction="http://tempuri.org/ISanPhamService/SuaResponse")]
        void Sua(WebForm.SanPhamServiceReference.SanPham sp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISanPhamService/Sua_DonGia", ReplyAction="http://tempuri.org/ISanPhamService/Sua_DonGiaResponse")]
        void Sua_DonGia(WebForm.SanPhamServiceReference.SanPham sp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISanPhamService/Xoa", ReplyAction="http://tempuri.org/ISanPhamService/XoaResponse")]
        void Xoa(WebForm.SanPhamServiceReference.SanPham sp);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISanPhamServiceChannel : WebForm.SanPhamServiceReference.ISanPhamService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SanPhamServiceClient : System.ServiceModel.ClientBase<WebForm.SanPhamServiceReference.ISanPhamService>, WebForm.SanPhamServiceReference.ISanPhamService {
        
        public SanPhamServiceClient() {
        }
        
        public SanPhamServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SanPhamServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SanPhamServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SanPhamServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet LaySP_ID() {
            return base.Channel.LaySP_ID();
        }
        
        public WebForm.SanPhamServiceReference.SanPham[] HienThiSanPhamFull() {
            return base.Channel.HienThiSanPhamFull();
        }
        
        public WebForm.SanPhamServiceReference.SanPham[] HienThiSanPhamMoi() {
            return base.Channel.HienThiSanPhamMoi();
        }
        
        public WebForm.SanPhamServiceReference.SanPham[] HienThiSanPhamCungLoai(WebForm.SanPhamServiceReference.SanPham sp) {
            return base.Channel.HienThiSanPhamCungLoai(sp);
        }
        
        public WebForm.SanPhamServiceReference.SanPham[] HienThiSanPhamNhaSX(WebForm.SanPhamServiceReference.SanPham sp) {
            return base.Channel.HienThiSanPhamNhaSX(sp);
        }
        
        public WebForm.SanPhamServiceReference.SanPham[] TimKiemSanPham(string tensp, int nhasxid, decimal dongiatu, decimal dongiaden) {
            return base.Channel.TimKiemSanPham(tensp, nhasxid, dongiatu, dongiaden);
        }
        
        public System.Data.DataSet ChiTietSanPham(WebForm.SanPhamServiceReference.SanPham sp) {
            return base.Channel.ChiTietSanPham(sp);
        }
        
        public System.Data.DataSet ThongTinNhapSP(WebForm.SanPhamServiceReference.PhieuNhap pn) {
            return base.Channel.ThongTinNhapSP(pn);
        }
        
        public void Them(WebForm.SanPhamServiceReference.SanPham sp) {
            base.Channel.Them(sp);
        }
        
        public void Sua(WebForm.SanPhamServiceReference.SanPham sp) {
            base.Channel.Sua(sp);
        }
        
        public void Sua_DonGia(WebForm.SanPhamServiceReference.SanPham sp) {
            base.Channel.Sua_DonGia(sp);
        }
        
        public void Xoa(WebForm.SanPhamServiceReference.SanPham sp) {
            base.Channel.Xoa(sp);
        }
    }
}
